name: "Continuous Integration PR"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache -t housing-price-predictor-api:pr-${{ github.event.pull_request.number }} .

    # TODO run tests
    # - name: Run tests
    #   run: echo "Running tests..."      
